### ISSUE TITLE
Setup Continuous Integration

### ISSUE THREAD

**Issue by agdula** [DiffKit/DiffKit#1]
It's a must have for a project so we have to have it. Lots of OSS project use https://travis-ci.org. I think its easy to setup so If nobody has better idea lets go for it

**Comment by paulsaurels** [comment]
Cool... i ´ll ckeck it !!

**Comment by agdula** [comment]
test fails on travis with this exceptoin

```
org.h2.jdbc.JdbcSQLException: Table "LHS2" already exists; SQL statement:
CREATE TABLE LHS2
(
        column1     VARCHAR(20) NOT NULL,
        column2     VARCHAR,
        column3     VARCHAR,
        CONSTRAINT pk_LHS2 PRIMARY KEY (column1))
 [42101-153]
    at org.h2.message.DbException.getJdbcSQLException(DbException.java:327) [h2-1.3.153.jar:1.3.153]
    at org.h2.message.DbException.get(DbException.java:167) [h2-1.3.153.jar:1.3.153]
    at org.h2.message.DbException.get(DbException.java:144) [h2-1.3.153.jar:1.3.153]
    at org.h2.command.ddl.CreateTable.update(CreateTable.java:108) [h2-1.3.153.jar:1.3.153]
    at org.h2.command.CommandContainer.update(CommandContainer.java:69) [h2-1.3.153.jar:1.3.153]
    at org.h2.command.Command.executeUpdate(Command.java:212) [h2-1.3.153.jar:1.3.153]
    at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:177) [h2-1.3.153.jar:1.3.153]
    at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:152) [h2-1.3.153.jar:1.3.153]
    at org.diffkit.util.DKSqlUtil.executeUpdate(DKSqlUtil.java:340) [classes/:na]
    at org.diffkit.db.DKDatabase.createTable(DKDatabase.java:208) [classes/:na]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) [na:1.8.0_31]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) [na:1.8.0_31]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) [na:1.8.0_31]
    at java.lang.reflect.Method.invoke(Method.java:483) [na:1.8.0_31]
    at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoCachedMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:229) [groovy-all-1.7.3.jar:1.7.3]
    at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:52) [groovy-all-1.7.3.jar:1.7.3]
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:40) [groovy-all-1.7.3.jar:1.7.3]
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:117) [groovy-all-1.7.3.jar:1.7.3]
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125) [groovy-all-1.7.3.jar:1.7.3]
    at org.diffkit.diff.engine.tst.TestEngine.testSameModelFromDB(TestEngine.groovy:150) [test-classes/:na]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) [na:1.8.0_31]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) [na:1.8.0_31]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) [na:1.8.0_31]
    at java.lang.reflect.Method.invoke(Method.java:483) [na:1.8.0_31]
    at junit.framework.TestCase.runTest(TestCase.java:168) [junit-4.8.2.jar:na]
    at junit.framework.TestCase.runBare(TestCase.java:134) [junit-4.8.2.jar:na]
    at junit.framework.TestResult$1.protect(TestResult.java:110) [junit-4.8.2.jar:na]
    at junit.framework.TestResult.runProtected(TestResult.java:128) [junit-4.8.2.jar:na]
    at junit.framework.TestResult.run(TestResult.java:113) [junit-4.8.2.jar:na]
    at junit.framework.TestCase.run(TestCase.java:124) [junit-4.8.2.jar:na]
    at junit.framework.TestSuite.runTest(TestSuite.java:243) [junit-4.8.2.jar:na]
    at junit.framework.TestSuite.run(TestSuite.java:238) [junit-4.8.2.jar:na]
    at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83) [junit-4.8.2.jar:na]
    at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252) [surefire-junit4-2.12.4.jar:2.12.4]
    at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141) [surefire-junit4-2.12.4.jar:2.12.4]
    at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112) [surefire-junit4-2.12.4.jar:2.12.4]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) [na:1.8.0_31]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) [na:1.8.0_31]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) [na:1.8.0_31]
    at java.lang.reflect.Method.invoke(Method.java:483) [na:1.8.0_31]
    at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189) [surefire-api-2.12.4.jar:2.12.4]
    at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165) [surefire-booter-2.12.4.jar:2.12.4]
    at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85) [surefire-booter-2.12.4.jar:2.12.4]
    at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115) [surefire-booter-2.12.4.jar:2.12.4]
    at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75) [surefire-booter-2.12.4.jar:2.12.4]
lhsFile->/home/travis/build/DiffKit/DiffKit/target/test-classes/org/diffkit/diff/engine/tst/lhs1.csv
rhsFile->/home/travis/build/DiffKit/DiffKit/target/test-classes/org/diffkit/diff/engine/tst/rhs1.csv
```

**Comment by agdula** [comment]
Tests fixed.
Build is passing, Can close this issue
